---
title: "Sobre mi"
description: |
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hola! 

Mi nombre es Malena De Baere y soy Licenciada en Trabajo Social de la Universidad de Buenos Aires. Actualmente me encuentro finalizando la Maestría en Economía Urbana de la Universidad Torcuato Di Tella. Durante mi carrera profesional he transitado por distintos espacios relacionados al Hábitat, lo cual me ha motivado a seguir formandome en estos aspectos. 

Este sitio fue realizado en el marco de la materia de "Instrumentos de Análisis Territorial Aplicados a Estudios Urbanos", a cargo de los profesores Juan Pablo Ruiz Nicolini (alias "el Tuqu") y Pablo Tiscornia. Aquí aprendemos ha utilizar(o al menos intentamos) lenguaje de programación con "R Studio". Esta herramienta permité poder trabajar con grandes bases de datos para realizar análisis de forma más sencilla, rápida y ( si no hay errores) confiable. 

Te dejo los links a los repositorios de otros trabajos que hemos realizado en la materia:

- **Trabajo Práctico I**  : vinculado al análisis de la utilización de las lineas de subte durante el año 2020
https://github.com/Malenaadb/TP1_IAU2

- **Trabajo Práctico II**  : vinculado a la identificación del registro de poblaciones originarias a lo largo de nuestro país
https://github.com/Malenaadb/IAU2_TP2

Espero te haya interesado lo realizado. 


¡Y muchas gracias por haber llegado hasta acá! 



